POSIX compliance

diff --git a/libretranslate b/libretranslate
--- a/libretranslate
+++ b/libretranslate
@@ -1,46 +1,36 @@
-if [ $LIBRETRANSLATE_URL ]
-then
-    url=$LIBRETRANSLATE_URL
-else
-    url="https://translate.argosopentech.com/"
-fi
+#!/bin/sh
+#
+# Shell script for working with the LibreTranslate API
 
-if [ $LIBRETRANSLATE_API_KEY ]
-then
-    api_key_flag="-F \"api_key=${$LIBRETRANSLATE_API_KEY}\""
-else
-    api_key_flag=""
-fi
+url=${LIBRETRANSLATE_URL:-'https://translate.argosopentech.com/'}
 
-curl_args="--silent --show-error "
+[ -n "$LIBRETRANSLATE_API_KEY" ] && api_key_flag="-F \"api_key=${LIBRETRANSLATE_API_KEY}\""
 
-fun=$1
-if [ $fun == "translate" ]
-then
-    source=$2
-    target=$3
-    q=$4
-    curl -X POST \
-            $curl_args \
-            -F "q=$q" \
-            -F "source=$source" \
-            -F "target=$target" \
-	    $api_key_flag \
-            "${url}translate"
-elif [ $fun == "detect" ]
-then
-    q=$2
-    curl -X POST \
-            $curl_args \
-            -F "q=$q" \
-	    $api_key_flag \
-            "${url}detect"
-elif [ $fun == "languages" ]
-then
-    curl -X POST \
-            $curl_args \
-            "${url}languages"
-else
-    echo "Invalid function"
-    exit 1
-fi
+curl_args='--silent --show-error '
+
+case "$1" in
+	'translate')
+		source=$2
+    		target=$3
+    		q=$4
+
+    		curl -X POST \
+            		$curl_args \
+            		-F "q=$q" \
+            		-F "source=$source" \
+            		-F "target=$target" \
+	    		$api_key_flag \
+            		"${url}translate" ;;
+	'detect')
+		q=$2
+    		curl -X POST \
+            		$curl_args \
+            		-F "q=$q" \
+	    		$api_key_flag \
+            		"${url}detect" ;;
+	'languages')
+		curl -X POST \
+            		$curl_args \
+            		"${url}languages" ;;
+	*) echo 'Invalid function' && exit 1 ;;
+esac
